# Generated by Django 5.1.6 on 2025-02-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='image',
            field=models.ImageField(null=True, upload_to='product_img/'),
        ),
    ]
